<a href="https://colab.research.google.com/github/MHILAL-Dev2026/data-science-2026/blob/main/Pertemuan2_MuhammadHilalADM_250401020122.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
URL = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"
df = pd.read_csv(URL)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [9]:
print("Q1: Berapa jumlah baris dan kolom pada dataset Titanic? Kolom apa saja yang tersedia?")

print("Baris:", df.shape)
print("Kolom:", df.columns.tolist())

Q1: Berapa jumlah baris dan kolom pada dataset Titanic? Kolom apa saja yang tersedia?
Baris: (891, 12)
Kolom: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [13]:
print("Q2: Kolom mana saja yang memiliki missing values? Berapa jumlah dan proporsinya (%) per kolom?")

missing = df.isnull().sum()
percent = (missing / len(df)) * 100

missing_df = pd.DataFrame({
    'Missing Count': missing,
    'Persentase (%)': percent
})

missing_df

Q2: Kolom mana saja yang memiliki missing values? Berapa jumlah dan proporsinya (%) per kolom?

             Missing Count  Persentase (%)
PassengerId              0        0.000000
Survived                 0        0.000000
Pclass                   0        0.000000
Name                     0        0.000000
Sex                      0        0.000000
Age                    177       19.865320
SibSp                    0        0.000000
Parch                    0        0.000000
Ticket                   0        0.000000
Fare                     0        0.000000
Cabin                  687       77.104377
Embarked                 2        0.224467

In [14]:
print("Q3: Berapa persen penumpang yang selamat (Survived=1)? Gunakan operasi NumPy atau Pandas.")

survival_rate = df['Survived'].mean() * 100
print(f"Persentase selamat: {survival_rate:.2f}%")

Q3: Berapa persen penumpang yang selamat (Survived=1)? Gunakan operasi NumPy atau Pandas.
Persentase selamat: 38.38%

In [17]:
print("Q4: Filter penumpang wanita dari kelas 1 (Pclass=1). Berapa jumlahnya dan berapa rata- rata usianya?")

female_class1 = df[(df['Sex'] == 'female') & (df['Pclass'] == 1)]

jumlah = len(female_class1)
rata_umur = female_class1['Age'].mean()

print("Jumlah:", jumlah)
print("Rata-rata umur:", rata_umur)

Q4: Filter penumpang wanita dari kelas 1 (Pclass=1). Berapa jumlahnya dan berapa rata- rata usianya?
Jumlah: 94
Rata-rata umur: 34.61176470588235

In [23]:
print("Q5: Gunakan groupby untuk menghitung tingkat keselamatan (mean Survived) per kelas penumpang. Kelas mana yang paling tinggi?")

survival_by_class = df.groupby('Pclass')['Survived'].mean()
print(survival_by_class)

print("Kelas paling tinggi = Kelas 1")

Q5: Gunakan groupby untuk menghitung tingkat keselamatan (mean Survived) per kelas penumpang. Kelas mana yang paling tinggi?
Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64
Kelas paling tinggi = Kelas 1

In [22]:
print("Buat analisis tambahan berdasarkan variabel lain yang Anda anggap menarik. Sertakan interpretasi singkat.")

survival_by_gender = df.groupby('Sex')['Survived'].mean()
print(survival_by_gender)

print("Interpretasi: Mengambil variabel Sex dengan Survived, menghasilkan interpretasi perempuan memiliki probabilitas selamat jauh lebih tinggi dibanding laki-laki, mengindikasikan adanya prioritas evakuasi berbasis gender.")

Buat analisis tambahan berdasarkan variabel lain yang Anda anggap menarik. Sertakan interpretasi singkat.
Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64
Interpretasi: Mengambil variabel Sex dengan Survived, menghasilkan interpretasi perempuan memiliki probabilitas selamat jauh lebih tinggi dibanding laki-laki, mengindikasikan adanya prioritas evakuasi berbasis gender.